version: '3.8'
services:
  api:
    build: .
    ports:
      - '3001:3001' # API rodando na porta 3001 do host
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://postgres:password@localhost:5433/bank_api
    volumes:
      - .:/app
    command: npm run start:dev

  postgres:
    image: postgres:13
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: bank_api
    ports:
      - '5433:5432' # Banco de dados rodando na porta 5433 do host
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
